name: Laravel Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.2.16
        env:
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: food-expiry-date-reminder
        ports:
          - 3308:3308
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --prefer-dist

    - name: Generate Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_HOST: localhost
        DB_PORT: 3308
        DB_DATABASE: food-expiry-date-reminder
        DB_USERNAME: root
        DB_PASSWORD:
      run: vendor/bin/phpunit
